import { build } from "esbuild";

await build({
  entryPoints: [
    "src/accent-css.ts",
    "src/index.ts",
    "src/locales.ts",
    "src/model.ts",
    "src/persistence.ts",
    "src/palettes.ts",
    "src/schema.ts",
    "src/think-markdown.ts",
    "src/think-scheduler.ts"
  ],
  outdir: "dist",
  bundle: false,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  legalComments: "none",
  sourcemap: false
});

await build({
  entryPoints: [new URL("../src/client-entry.ts", import.meta.url).pathname],
  outfile: new URL("../dist/client.js", import.meta.url).pathname,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  legalComments: "none",
  sourcemap: false,
  banner: {
    js: "// Generated by scripts/build-client.mjs. Do not edit directly."
  },
  external: [
    "react",
    "@deepseek-ai/dsh-client-runtime/client",
    "@deepseek-ai/dsh-client-ui-primitives"
  ]
});
